[workspace]
resolver = "2"
members = ["diff2html", "diff2html-cli"]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/rtfpessoa/diff2html-rs"
homepage = "https://diff2html.xyz/"
